### ISSUE TITLE
Error in make: mkoctfile: not found

### ISSUE THREAD

**Issue by arthur-e** [tmullins/hdf5oct#17]
On Ubuntu 18.04; Octave installed with `apt install octave`.

In the source directory, `make` fails with error:

```
CXX=h5c++ mkoctfile -g -c h5read.cc
/bin/sh: 1: mkoctfile: not found
makefile:19: recipe for target 'h5read.o' failed
make: *** [h5read.o] Error 127
```

**Comment by mcaniot** [comment]
you need to install octave-pkg-dev with the command  `sudo apt-get install octave-pkg-dev`

**Comment by arthur-e** [comment]
That seems to have fixed it. Thanks!
