### ISSUE TITLE
License for integration into Octave core

### ISSUE THREAD

**Issue by stegro** [tmullins/hdf5oct#2]
Hello, 

I was wondering if you would allow me to add hdf5oct to the GNU octave core under GPLv3. I found that you originally chose the LGPLv3 so I am guessing you might not be opposed to the GPL. Of course, you will still be free to keep it on your website or github under another license, it will always be yours to create as many copies under as many different licenses as you want.

If you agree, my fork will be added to GNU octave, under GPLv3+ and
with you, me and the other contributors as its copyright owner.

best regards

Stefan

*edit: I just realize that asking you for permission might eventually be obsolete, according to this table:*
http://www.gnu.org/licenses/gpl-faq.html#AllCompatibility
*But anyway, I hope it's welcome and you don't mind that we integrate it.*

**Comment by tmullins** [comment]
Sure, you can add it to GNU octave. I'm glad to see the library being used and improved.
